# Указываем директорию, где будем хранить файлы (путь указывается относительно корня)
file:
  directory: files

spring:
  h2.console.enabled: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/accidents
    username: postgres
    password: Okhorzina2912
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      # Указываем максимальный размер файла (по умолчанию 1MB, что неудобно, т.к. некоторые изображения могут весить много)
      max-file-size: 10MB
  mandatory-file-encoding: UTF-8
# Project encoding settings
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true